#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DEMO_DIR="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
PROJECT_DIR="$(cd -- "${DEMO_DIR}/../.." >/dev/null 2>&1 && pwd)"

: "${DEMO_ENV_FILE:=${DEMO_DIR}/demo.env}"
if [[ ! -f "${DEMO_ENV_FILE}" ]]; then
  printf 'ERROR demo configuration file is missing: %s\n' "${DEMO_ENV_FILE}" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "${DEMO_ENV_FILE}"

: "${DEMO_STATE_DIR:=/tmp/hami-dra-kind-vnpu-demo}"
STATE_FILE="${DEMO_STATE_DIR}/runtime.env"

if [[ -f "${STATE_FILE}" ]]; then
  # The file is generated by save_state and only contains runtime discoveries.
  # shellcheck disable=SC1090
  source "${STATE_FILE}"
fi

: "${KIND_CLUSTER_NAME:=hami-dra-vnpu-demo}"
: "${KUBECONFIG:=${DEMO_STATE_DIR}/kubeconfig}"
: "${KIND_NODE_IMAGE:=kindest/node:v1.34.0}"
: "${CUSTOM_KIND_NODE_IMAGE:=kindest/node:v1.34.0-cgroupfs-cdi-ascend}"
: "${KIND_CGROUP_MODE:=auto}"
: "${KIND_RESOLVED_CGROUP_MODE:=}"
: "${KIND_CLUSTER_IMAGE:=}"
: "${DAVINCI_DEVICE_NODES:=}"
: "${DRIVER_IMAGE_REPOSITORY:=registry.example.com/ascend-dra-driver}"
: "${DRIVER_IMAGE_TAG:=demo-vnpu-softsplit-$(date +%Y%m%d%H%M%S)}"
: "${DRIVER_IMAGE:=${DRIVER_IMAGE_REPOSITORY}:${DRIVER_IMAGE_TAG}}"
: "${CANN_IMAGE:=ascendai/cann:9.0.0-devel}"
: "${WORKLOAD_IMAGE:=${CANN_IMAGE}}"
: "${GOLANG_VERSION:=1.26.0}"
GOLANG_IMAGE="golang:${GOLANG_VERSION}"
: "${DRIVER_NAMESPACE:=ascend-dra-demo}"
: "${TEST_NAMESPACE:=ascend-dra-vnpu-demo}"
: "${HELM_RELEASE:=ascend-dra-driver}"
: "${WORKER:=${KIND_CLUSTER_NAME}-worker}"
: "${RUN_GO_TESTS:=true}"
: "${SKIP_EXISTING_IMAGE_BUILDS:=true}"
: "${KIND_VERSION:=v0.30.0}"
: "${DEVICE_SHARE_CHIP_ID:=0}"

export KUBECONFIG

color_blue=$'\033[0;34m'
color_green=$'\033[0;32m'
color_yellow=$'\033[0;33m'
color_red=$'\033[0;31m'
color_reset=$'\033[0m'

section() {
  printf '\n%s==> %s%s\n' "${color_blue}" "$*" "${color_reset}"
}

success() {
  printf '%sPASS%s %s\n' "${color_green}" "${color_reset}" "$*"
}

warn() {
  printf '%sWARN%s %s\n' "${color_yellow}" "${color_reset}" "$*" >&2
}

fail() {
  printf '%sERROR%s %s\n' "${color_red}" "${color_reset}" "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    fail "required command is missing: $1"
}

require_file() {
  [[ -f "$1" ]] || fail "required file is missing: $1"
}

require_directory() {
  [[ -d "$1" ]] || fail "required directory is missing: $1"
}

require_character_device() {
  [[ -c "$1" ]] || fail "required character device is missing: $1"
}

require_boolean() {
  local name=$1
  local value=$2

  case "${value}" in
  true | false) ;;
  *) fail "${name} must be true or false: ${value}" ;;
  esac
}

wait_for_pod_log_pattern() {
  local namespace=$1
  local pod=$2
  local pattern=$3
  local output_file=$4
  local max_attempts=${5:-60}
  local retry_delay=${6:-1}
  local temporary_file="${output_file}.tmp"
  local attempt

  [[ "${max_attempts}" =~ ^[1-9][0-9]*$ ]] ||
    fail "max_attempts must be a positive integer: ${max_attempts}"

  for ((attempt = 1; attempt <= max_attempts; attempt++)); do
    if kubectl -n "${namespace}" logs "${pod}" > "${temporary_file}"; then
      mv "${temporary_file}" "${output_file}"
      if grep -Eq "${pattern}" "${output_file}"; then
        cat "${output_file}"
        return 0
      fi
    fi

    if ((attempt < max_attempts)); then
      sleep "${retry_delay}"
    fi
  done

  [[ ! -f "${output_file}" ]] || cat "${output_file}" >&2
  return 1
}

discover_davinci_device_nodes() {
  local device_root=${1:-/dev}
  local node
  local found=false

  while IFS= read -r node; do
    [[ "${node##*/}" =~ ^davinci[0-9]+$ ]] || continue
    [[ -c "${node}" ]] || continue
    found=true
    printf '%s\n' "${node}"
  done < <(
    find "${device_root}" -maxdepth 1 -type c \
      -name 'davinci[0-9]*' -print 2>/dev/null |
      LC_ALL=C sort -V
  )

  [[ "${found}" == "true" ]] ||
    fail "no /dev/davinci<number> character devices were found under ${device_root}"
}

kind_davinci_device_mounts() {
  local nodes=$1
  local node

  while IFS= read -r node; do
    [[ -n "${node}" ]] || continue
    printf '%s\n' \
      "      - hostPath: ${node}" \
      "        containerPath: ${node}"
  done <<< "${nodes}"
}

resolve_kind_cgroup_mode() {
  local requested_mode=$1
  local docker_cgroup_version=$2

  case "${requested_mode}" in
  auto)
    case "${docker_cgroup_version}" in
    1 | v1)
      printf 'cgroupfs\n'
      ;;
    2 | v2)
      printf 'systemd\n'
      ;;
    *)
      fail "cannot select a Kind cgroup mode from Docker cgroup version: ${docker_cgroup_version:-unknown}"
      ;;
    esac
    ;;
  cgroupfs | systemd)
    printf '%s\n' "${requested_mode}"
    ;;
  *)
    fail "KIND_CGROUP_MODE must be auto, cgroupfs, or systemd: ${requested_mode}"
    ;;
  esac
}

select_kind_cluster_image() {
  case "${KIND_RESOLVED_CGROUP_MODE}" in
  cgroupfs)
    KIND_CLUSTER_IMAGE="${CUSTOM_KIND_NODE_IMAGE}"
    ;;
  systemd)
    KIND_CLUSTER_IMAGE="${KIND_NODE_IMAGE}"
    ;;
  *)
    fail "Kind cgroup mode has not been resolved: ${KIND_RESOLVED_CGROUP_MODE:-empty}"
    ;;
  esac
}

kind_containerd_config_patches() {
  [[ "${KIND_RESOLVED_CGROUP_MODE}" == "systemd" ]] || return 0

  printf '%s\n' \
    'containerdConfigPatches:' \
    '  - |-' \
    '    [plugins."io.containerd.grpc.v1.cri"]' \
    '      enable_cdi = true' \
    '    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.ascend]' \
    '      runtime_type = "io.containerd.runc.v2"' \
    '      base_runtime_spec = "/etc/containerd/cri-base.json"' \
    '    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.ascend.options]' \
    '      BinaryName = "/usr/local/bin/ascend-docker-runtime-wrapper"' \
    '      SystemdCgroup = true'
}

kind_kubelet_cgroup_patch() {
  [[ "${KIND_RESOLVED_CGROUP_MODE}" == "cgroupfs" ]] || return 0

  printf '%s\n' \
    '    kubeadmConfigPatches:' \
    '      - |-' \
    '        kind: KubeletConfiguration' \
    '        apiVersion: kubelet.config.k8s.io/v1beta1' \
    '        cgroupDriver: cgroupfs'
}

cluster_exists() {
  [[ -x "${KIND_BIN:-}" ]] &&
    "${KIND_BIN}" get clusters 2>/dev/null |
      grep -Fxq "${KIND_CLUSTER_NAME}"
}

render_template() {
  python3 "${SCRIPT_DIR}/render-template.py" "$@"
}

save_state() {
  mkdir -p "${DEMO_STATE_DIR}"
  local temporary="${STATE_FILE}.tmp"
  {
    printf '# Generated runtime state; edit demo/kind-vnpu/demo.env instead.\n'
    local name
    for name in \
      KIND_RESOLVED_CGROUP_MODE KIND_CLUSTER_IMAGE KIND_BIN \
      DOCKER_CGROUP_DRIVER DOCKER_CGROUP_VERSION \
      NPU_SMI_HOST_PATH DAVINCI_DEVICE_NODES \
      DEVICE_SHARE_CARD_IDS \
      UID_A UID_B; do
      if declare -p "${name}" >/dev/null 2>&1; then
        printf 'if [[ -z "${%s:-}" ]]; then\n' "${name}"
        printf '  %s=%q\n' "${name}" "${!name}"
        printf 'fi\n'
      fi
    done
  } > "${temporary}"
  mv "${temporary}" "${STATE_FILE}"
}

record_demo_image() {
  local image=$1
  local images_file="${DEMO_STATE_DIR}/demo-images.expected"
  mkdir -p "${DEMO_STATE_DIR}"
  touch "${images_file}"
  if ! grep -Fxq "${image}" "${images_file}"; then
    printf '%s\n' "${image}" >> "${images_file}"
  fi
}

kind_container_ids() {
  docker ps -a -q \
    --filter "label=io.x-k8s.kind.cluster=${KIND_CLUSTER_NAME}" |
    LC_ALL=C sort
}

snapshot_images() {
  docker image ls --no-trunc --digests \
    --format '{{.Repository}}:{{.Tag}} {{.ID}} {{.Digest}}' |
    LC_ALL=C sort
}

verify_preexisting_images() {
  local before="${DEMO_STATE_DIR}/docker-images.before"
  local after="${DEMO_STATE_DIR}/docker-images.after"
  local missing="${DEMO_STATE_DIR}/preexisting-images.missing"

  [[ -f "${before}" ]] || fail "image baseline is missing: ${before}"
  snapshot_images > "${after}"
  LC_ALL=C comm -23 "${before}" "${after}" > "${missing}"
  [[ ! -s "${missing}" ]] || {
    cat "${missing}" >&2
    fail "one or more pre-existing Docker image references are missing"
  }
}
