#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DEMO_DIR="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
PROJECT_DIR="$(cd -- "${DEMO_DIR}/../.." >/dev/null 2>&1 && pwd)"

: "${DEMO_STATE_DIR:=/tmp/hami-dra-kind-vnpu-demo}"
STATE_FILE="${DEMO_STATE_DIR}/demo-env.sh"

if [[ -f "${STATE_FILE}" ]]; then
  # The file is generated by save_state below and contains shell-quoted values.
  # shellcheck disable=SC1090
  source "${STATE_FILE}"
fi

: "${KIND_CLUSTER_NAME:=hami-dra-vnpu-demo}"
: "${KUBECONFIG:=${DEMO_STATE_DIR}/kubeconfig}"
: "${KIND_NODE_IMAGE:=kindest/node:v1.34.0}"
: "${BASE_CUSTOM_KIND_NODE_IMAGE:=kindest/node:v1.34.0-cgroupfs-cdi}"
: "${CUSTOM_KIND_NODE_IMAGE:=kindest/node:v1.34.0-cgroupfs-cdi-ascend}"
: "${DRIVER_IMAGE_REPOSITORY:=registry.example.com/ascend-dra-driver}"
: "${DRIVER_IMAGE_TAG:=demo-vnpu-softsplit-$(date +%Y%m%d%H%M%S)}"
: "${DRIVER_IMAGE:=${DRIVER_IMAGE_REPOSITORY}:${DRIVER_IMAGE_TAG}}"
: "${CANN_IMAGE:=ascendai/cann:9.0.0-devel}"
: "${GOLANG_VERSION:=1.26.0}"
GOLANG_IMAGE="golang:${GOLANG_VERSION}"
: "${DRIVER_NAMESPACE:=ascend-dra-demo}"
: "${TEST_NAMESPACE:=ascend-dra-vnpu-demo}"
: "${HELM_RELEASE:=ascend-dra-driver}"
: "${WORKER:=${KIND_CLUSTER_NAME}-worker}"
: "${RUN_GO_TESTS:=true}"
: "${REUSE_DRIVER_IMAGE:=false}"
: "${KIND_VERSION:=v0.30.0}"
: "${DEVICE_SHARE_CHIP_ID:=0}"

export KUBECONFIG

color_blue=$'\033[0;34m'
color_green=$'\033[0;32m'
color_yellow=$'\033[0;33m'
color_red=$'\033[0;31m'
color_reset=$'\033[0m'

section() {
  printf '\n%s==> %s%s\n' "${color_blue}" "$*" "${color_reset}"
}

success() {
  printf '%sPASS%s %s\n' "${color_green}" "${color_reset}" "$*"
}

warn() {
  printf '%sWARN%s %s\n' "${color_yellow}" "${color_reset}" "$*" >&2
}

fail() {
  printf '%sERROR%s %s\n' "${color_red}" "${color_reset}" "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    fail "required command is missing: $1"
}

require_file() {
  [[ -f "$1" ]] || fail "required file is missing: $1"
}

require_directory() {
  [[ -d "$1" ]] || fail "required directory is missing: $1"
}

require_character_device() {
  [[ -c "$1" ]] || fail "required character device is missing: $1"
}

cluster_exists() {
  [[ -x "${KIND_BIN:-}" ]] &&
    "${KIND_BIN}" get clusters 2>/dev/null |
      grep -Fxq "${KIND_CLUSTER_NAME}"
}

render_template() {
  python3 "${SCRIPT_DIR}/render-template.py" "$@"
}

save_state() {
  mkdir -p "${DEMO_STATE_DIR}"
  local temporary="${STATE_FILE}.tmp"
  {
    printf '# Generated by demo/kind-vnpu; safe to source.\n'
    printf 'export '
    printf '%q=' DEMO_STATE_DIR
    printf '%q\n' "${DEMO_STATE_DIR}"
    local name
    for name in \
      KIND_CLUSTER_NAME KUBECONFIG KIND_NODE_IMAGE \
      BASE_CUSTOM_KIND_NODE_IMAGE CUSTOM_KIND_NODE_IMAGE \
      DRIVER_IMAGE_REPOSITORY DRIVER_IMAGE_TAG DRIVER_IMAGE \
      CANN_IMAGE GOLANG_VERSION DRIVER_NAMESPACE TEST_NAMESPACE HELM_RELEASE \
      WORKER RUN_GO_TESTS REUSE_DRIVER_IMAGE KIND_VERSION KIND_BIN \
      NPU_SMI_HOST_PATH DEVICE_SHARE_CARD_IDS DEVICE_SHARE_CHIP_ID \
      UID_A UID_B; do
      if declare -p "${name}" >/dev/null 2>&1; then
        printf 'export %s=%q\n' "${name}" "${!name}"
      fi
    done
  } > "${temporary}"
  mv "${temporary}" "${STATE_FILE}"
}

record_demo_image() {
  local image=$1
  local images_file="${DEMO_STATE_DIR}/demo-images.expected"
  mkdir -p "${DEMO_STATE_DIR}"
  touch "${images_file}"
  if ! grep -Fxq "${image}" "${images_file}"; then
    printf '%s\n' "${image}" >> "${images_file}"
  fi
}

kind_container_ids() {
  docker ps -a -q \
    --filter "label=io.x-k8s.kind.cluster=${KIND_CLUSTER_NAME}" |
    LC_ALL=C sort
}

snapshot_images() {
  docker image ls --no-trunc --digests \
    --format '{{.Repository}}:{{.Tag}} {{.ID}} {{.Digest}}' |
    LC_ALL=C sort
}

verify_preexisting_images() {
  local before="${DEMO_STATE_DIR}/docker-images.before"
  local after="${DEMO_STATE_DIR}/docker-images.after"
  local missing="${DEMO_STATE_DIR}/preexisting-images.missing"

  [[ -f "${before}" ]] || fail "image baseline is missing: ${before}"
  snapshot_images > "${after}"
  LC_ALL=C comm -23 "${before}" "${after}" > "${missing}"
  [[ ! -s "${missing}" ]] || {
    cat "${missing}" >&2
    fail "one or more pre-existing Docker image references are missing"
  }
}
